# Generated by Django 5.1.3 on 2025-03-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=120, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "time_limit",
                    models.IntegerField(default=60, help_text="Time limit in minutes"),
                ),
                (
                    "required_score_to_pass",
                    models.IntegerField(
                        blank=True, help_text="required score in %", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Exam.exam"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier like A, B, C, etc.", max_length=5
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                (
                    "matching_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Exam.matchingexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        help_text="Identifier like A, B, C, etc.", max_length=5
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                (
                    "matching_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Exam.matchingexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Exam.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.CharField(max_length=500)),
                ("correct", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="Exam.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="Exam.matchinganswer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="Exam.matchingquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "correct_answer")},
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("score", models.FloatField()),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("matching", "Matching Exercise"),
                            ("Mixed", "Mixed Combined"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed results in JSON format",
                        null=True,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Exam.exam"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tracking_code"], name="Exam_result_trackin_99ba0a_idx"
                    ),
                    models.Index(
                        fields=["exam"], name="Exam_result_exam_id_784637_idx"
                    ),
                ],
            },
        ),
    ]
