# Generated by Django 5.1.3 on 2025-03-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("matching", "Matching"),
                    ("mixed", "Mixed"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
