# Generated by Django 5.1.3 on 2025-02-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Exam", "0002_examattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExamAttempt",
        ),
    ]
