# Generated by Django 5.1.3 on 2025-02-10 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Exam", "0003_delete_examattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="is_correct",
            new_name="correct",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="answer_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="exam",
            new_name="quiz",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="description",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="score",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="title",
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer_type",
        ),
        migrations.AddField(
            model_name="answer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="number_of_questions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="required_score_to_pass",
            field=models.IntegerField(
                blank=True, help_text="required score in %", null=True
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="time",
            field=models.IntegerField(
                blank=True, help_text="Duration of exam in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="topic",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="Exam.question",
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Exam.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
