# Generated by Django 5.1.3 on 2025-02-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Exam", "0009_alter_answer_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="choices",
            field=models.TextField(),
        ),
    ]
