# Generated by Django 5.1.3 on 2025-02-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Exam", "0011_alter_answer_choices"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("text", "exam")},
        ),
    ]
