# Generated by Django 5.1.3 on 2024-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('civil_status', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=50)),
                ('how_acquired', models.CharField(max_length=100)),
                ('last_residence', models.CharField(max_length=255)),
                ('date_of_arrival', models.DateField()),
                ('landing_certificate_no', models.CharField(max_length=100)),
                ('employment_contract', models.CharField(max_length=100)),
                ('employment_nature', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('present_company_name', models.CharField(max_length=100)),
                ('present_company_address', models.CharField(max_length=255)),
                ('education_files', models.FileField(blank=True, null=True, upload_to='education/')),
                ('board_exam_files', models.FileField(blank=True, null=True, upload_to='board_exams/')),
                ('work_experience_files', models.FileField(blank=True, null=True, upload_to='work_experience/')),
                ('training_files', models.FileField(blank=True, null=True, upload_to='training/')),
                ('education', models.JSONField(default=list)),
                ('board_exams', models.JSONField(default=list)),
                ('work_experience', models.JSONField(default=list)),
                ('trainings', models.JSONField(default=list)),
                ('documents', models.BooleanField(default=False)),
                ('compliance', models.BooleanField(default=False)),
                ('understanding', models.BooleanField(default=False)),
                ('certify', models.BooleanField(default=False)),
                ('permit_type', models.CharField(default='Permanent', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
