# Generated by Django 5.1.3 on 2024-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safety',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
