# Generated by Django 5.1.3 on 2024-12-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_safety_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='safety',
            name='notarized_file',
            field=models.FileField(blank=True, null=True, upload_to='notarized/'),
        ),
    ]
