# Generated by Django 5.1.3 on 2024-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_safety_notarized_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='safety',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
