# Generated by Django 5.1.3 on 2024-12-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_alter_safety_address_alter_safety_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safety',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='board_exam_files',
            field=models.FileField(null=True, upload_to='board_exams/'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='certify',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='citizenship',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='civil_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='compliance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='date_of_arrival',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='documents',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='education_files',
            field=models.FileField(null=True, upload_to='education/'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='employment_contract',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='employment_nature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='how_acquired',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='landing_certificate_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='last_residence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='notarized_file',
            field=models.FileField(null=True, upload_to='notarized/'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='permit_type',
            field=models.CharField(default='Permanent', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='present_company_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='present_company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='training_files',
            field=models.FileField(null=True, upload_to='training/'),
        ),
        migrations.AlterField(
            model_name='safety',
            name='understanding',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='work_experience_files',
            field=models.FileField(null=True, upload_to='work_experience/'),
        ),
    ]
