# Generated by Django 5.1.3 on 2024-12-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_alter_safety_address_alter_safety_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safety',
            old_name='board_exam_files',
            new_name='boardExamFiles',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='board_exams',
            new_name='boardExams',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='civil_status',
            new_name='civilStatus',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='contact_no',
            new_name='contactNo',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='date_of_arrival',
            new_name='dateOfArrival',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='education_files',
            new_name='educationFiles',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='employment_contract',
            new_name='employmentContract',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='employment_nature',
            new_name='employmentNature',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='how_acquired',
            new_name='howAcquired',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='landing_certificate_no',
            new_name='landingCertificateNo',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='last_residence',
            new_name='lastResidence',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='notarized_file',
            new_name='notarizedFile',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='place_of_birth',
            new_name='placeOfBirth',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='present_company_address',
            new_name='presentCompanyAddress',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='present_company_name',
            new_name='presentCompanyName',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='training_files',
            new_name='trainingFiles',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='work_experience',
            new_name='workExperience',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='work_experience_files',
            new_name='workExperienceFiles',
        ),
    ]
