# Generated by Django 5.1.3 on 2024-12-16 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0007_rename_board_exam_files_safety_boardexamfiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safety',
            name='notarizedFile',
        ),
        migrations.AddField(
            model_name='safety',
            name='notarizedFiles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='boardExamFiles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='educationFiles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='trainingFiles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='workExperienceFiles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='BoardExamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='board_exams/')),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_exam_files', to='safety.safety')),
            ],
        ),
        migrations.CreateModel(
            name='EducationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='education/')),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_files', to='safety.safety')),
            ],
        ),
        migrations.CreateModel(
            name='NotarizedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notarized/')),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notarized_files', to='safety.safety')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='training/')),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_files', to='safety.safety')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_experience/')),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_files', to='safety.safety')),
            ],
        ),
    ]
