# Generated by Django 5.1.3 on 2024-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0008_remove_safety_notarizedfile_safety_notarizedfiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safety',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
