# Generated by Django 5.1.3 on 2025-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0009_safety_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safety",
            name="boardExamFiles",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="boardExams",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="education",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="educationFiles",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="notarizedFiles",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="trainingFiles",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="trainings",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="workExperience",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="safety",
            name="workExperienceFiles",
            field=models.FileField(blank=True, default=list, null=True, upload_to=""),
        ),
    ]
