# Generated by Django 5.1.3 on 2025-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0010_alter_safety_boardexamfiles_alter_safety_boardexams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safety",
            name="educationFiles",
            field=models.FileField(
                blank=True, null=True, upload_to="safety/education_files/"
            ),
        ),
    ]
