# Generated by Django 5.1.3 on 2025-05-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0012_remove_safety_boardexamfiles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safety",
            name="boardExams",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="safety",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="safety",
            name="trainings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="safety",
            name="workExperience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
