# Generated by Django 5.1.3 on 2025-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0013_alter_safety_boardexams_alter_safety_education_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safety",
            name="board_exam_file",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="education_file",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="notarized_file",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="training_file",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="work_experience_file",
        ),
        migrations.AddField(
            model_name="safety",
            name="boardExamFiles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="educationFiles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="notarizedFiles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="trainingFiles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="workExperienceFiles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
