# Generated by Django 5.1.3 on 2025-05-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0014_remove_safety_board_exam_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationfile",
            name="safety",
        ),
        migrations.RemoveField(
            model_name="notarizedfile",
            name="safety",
        ),
        migrations.RemoveField(
            model_name="trainingfile",
            name="safety",
        ),
        migrations.RemoveField(
            model_name="workexperiencefile",
            name="safety",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="boardExamFiles",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="boardExams",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="education",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="educationFiles",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="notarizedFiles",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="trainingFiles",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="trainings",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="workExperience",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="workExperienceFiles",
        ),
        migrations.CreateModel(
            name="BoardExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_name", models.CharField(max_length=255)),
                ("date_taken", models.DateField()),
                ("license_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "safety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_exam_records",
                        to="safety.safety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("year_completed", models.IntegerField()),
                ("major", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "safety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_records",
                        to="safety.safety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SafetyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="safety_files/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("board_exam", "Board Exam"),
                            ("work_experience", "Work Experience"),
                            ("training", "Training"),
                            ("notarized", "Notarized"),
                            ("application", "Application Form"),
                            ("photo", "Photograph"),
                            ("fee", "Fee Payment"),
                            ("endorsement", "Endorsement"),
                            ("permit", "Permit"),
                            ("proof", "Proof Document"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "safety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="safety.safety",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("date_completed", models.DateField()),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "safety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to="safety.safety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                (
                    "safety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience_records",
                        to="safety.safety",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BoardExamFile",
        ),
        migrations.DeleteModel(
            name="EducationFile",
        ),
        migrations.DeleteModel(
            name="NotarizedFile",
        ),
        migrations.DeleteModel(
            name="TrainingFile",
        ),
        migrations.DeleteModel(
            name="WorkExperienceFile",
        ),
    ]
