# Generated by Django 5.1.3 on 2025-05-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0015_remove_educationfile_safety_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="safetyfile",
            options={},
        ),
        migrations.AddField(
            model_name="boardexam",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/board_exams/"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/education/"
            ),
        ),
        migrations.AddField(
            model_name="safety",
            name="application_form",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/application/"
            ),
        ),
        migrations.AddField(
            model_name="safety",
            name="notarized_document",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/notarized/"
            ),
        ),
        migrations.AddField(
            model_name="safety",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="safety_files/photos/"
            ),
        ),
        migrations.AddField(
            model_name="safety",
            name="proof_document",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/proof/"
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/training/"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="safety_files/work_experience/"
            ),
        ),
        migrations.CreateModel(
            name="TrainingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="training/")),
                (
                    "safety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_files",
                        to="safety.safety",
                    ),
                ),
            ],
        ),
    ]
