# Generated by Django 5.1.3 on 2025-05-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0016_alter_safetyfile_options_boardexam_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safety",
            name="application_form",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="notarized_document",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="safety",
            name="proof_document",
        ),
        migrations.AddField(
            model_name="safety",
            name="boardExamFiles",
            field=models.FileField(blank=True, null=True, upload_to="board_exams/"),
        ),
        migrations.AddField(
            model_name="safety",
            name="boardExams",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="educationFiles",
            field=models.FileField(blank=True, null=True, upload_to="education/"),
        ),
        migrations.AddField(
            model_name="safety",
            name="notarizedFiles",
            field=models.FileField(blank=True, null=True, upload_to="notarized/"),
        ),
        migrations.AddField(
            model_name="safety",
            name="trainingFiles",
            field=models.FileField(blank=True, null=True, upload_to="training/"),
        ),
        migrations.AddField(
            model_name="safety",
            name="trainings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="workExperience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="safety",
            name="workExperienceFiles",
            field=models.FileField(blank=True, null=True, upload_to="work_experience/"),
        ),
    ]
