# Generated by Django 5.1.3 on 2025-01-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safety', '0009_safety_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_diploma', models.FileField(blank=True, null=True, upload_to='checklist/college_diplomas/')),
                ('high_school_diploma', models.FileField(blank=True, null=True, upload_to='checklist/high_school_diplomas/')),
                ('valid_prc_license', models.FileField(blank=True, null=True, upload_to='checklist/prc_licenses/')),
                ('other_credentials', models.FileField(blank=True, null=True, upload_to='checklist/other_credentials/')),
                ('present_employer_notarized', models.FileField(blank=True, null=True, upload_to='checklist/present_employer/')),
                ('previous_employer', models.FileField(blank=True, null=True, upload_to='checklist/previous_employer/')),
                ('permanent_safety_fee', models.FileField(blank=True, null=True, upload_to='checklist/permanent_safety_fee/')),
                ('temporary_safety_fee', models.FileField(blank=True, null=True, upload_to='checklist/temporary_safety_fee/')),
                ('contractor_officials', models.FileField(blank=True, null=True, upload_to='checklist/contractor_officials/')),
                ('safety_manager', models.FileField(blank=True, null=True, upload_to='checklist/safety_manager/')),
                ('new_application_training', models.FileField(blank=True, null=True, upload_to='checklist/new_application_training/')),
                ('renewal_application_training', models.FileField(blank=True, null=True, upload_to='checklist/renewal_application_training/')),
                ('last_safety_permit', models.FileField(blank=True, null=True, upload_to='checklist/last_safety_permit/')),
                ('accident_report', models.FileField(blank=True, null=True, upload_to='checklist/accident_reports/')),
                ('safety_inspection_audit_report', models.FileField(blank=True, null=True, upload_to='checklist/safety_inspection_audit_reports/')),
                ('csh_committee_report', models.FileField(blank=True, null=True, upload_to='checklist/csh_committee_reports/')),
                ('osh_shp_program', models.FileField(blank=True, null=True, upload_to='checklist/osh_shp_programs/')),
                ('other_reports', models.TextField(blank=True, null=True)),
                ('complete_documents', models.BooleanField(default=False)),
                ('incomplete_documents', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=1000, null=True)),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='safety.safety')),
            ],
        ),
    ]
