# Generated by Django 5.1.3 on 2025-01-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='other_reportsFile',
            field=models.FileField(blank=True, null=True, upload_to='checklist/other_reports/'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='incomplete_documents',
            field=models.BooleanField(default=True),
        ),
    ]
