# Generated by Django 5.1.3 on 2025-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_checklist_other_reportsfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='accident_report_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='accident_report_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='college_diploma_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='college_diploma_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='contractor_officials_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='contractor_officials_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='csh_committee_report_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='csh_committee_report_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='high_school_diploma_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='high_school_diploma_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='last_safety_permit_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='last_safety_permit_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='new_application_training_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='new_application_training_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='osh_shp_program_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='osh_shp_program_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='other_credentials_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='other_credentials_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='other_reportsFile_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='other_reportsFile_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='permanent_safety_fee_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='permanent_safety_fee_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='present_employer_notarized_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='present_employer_notarized_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='previous_employer_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='previous_employer_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='renewal_application_training_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='renewal_application_training_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='safety_inspection_audit_report_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='safety_inspection_audit_report_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='safety_manager_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='safety_manager_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='temporary_safety_fee_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='temporary_safety_fee_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='valid_prc_license_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='valid_prc_license_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
