# Generated by Django 5.1.3 on 2025-04-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0003_checklist_accident_report_compliance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="college_diploma_compliance",
            new_name="Diploma_compliance",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="college_diploma_remarks",
            new_name="Diploma_remarks",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="high_school_diploma_compliance",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="high_school_diploma_remarks",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="other_credentials_compliance",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="other_credentials_remarks",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="valid_prc_license",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="valid_prc_license_compliance",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="valid_prc_license_remarks",
        ),
    ]
