# Generated by Django 5.1.3 on 2025-04-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checklist",
            "0005_rename_accident_report_compliance_checklist_accomplishment_compliance_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="Diploma_compliance",
            new_name="diploma_compliance",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="Diploma_remarks",
        ),
        migrations.AlterField(
            model_name="checklist",
            name="accomplishment_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="application_training_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="contractor_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="employer_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="last_safety_permit_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="photograph_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="safety_fee_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="checklist",
            name="diploma_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
