# Generated by Django 5.1.3 on 2025-04-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "checklist",
            "0006_rename_diploma_compliance_checklist_diploma_compliance_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="photograph",
            new_name="latest_photo",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="photograph_compliance",
            new_name="latest_photo_compliance",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="photograph_remarks",
            new_name="latest_photo_remarks",
        ),
    ]
