# Generated by Django 5.1.3 on 2025-04-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0007_rename_photograph_checklist_latest_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="application_training_compliance",
            new_name="application_compliance",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="application_training_remarks",
            new_name="application_remarks",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="last_safety_permit_compliance",
            new_name="permit_compliance",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="last_safety_permit_remarks",
            new_name="permit_remarks",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="latest_photo_compliance",
            new_name="photo_compliance",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="latest_photo_remarks",
            new_name="photo_remarks",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="safety_fee_compliance",
            new_name="safety_compliance",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="safety_fee_remarks",
            new_name="safety_remarks",
        ),
    ]
