# Generated by Django 5.1.3 on 2025-05-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0010_checkliststatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkliststatus",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Checklist Status",
                "verbose_name_plural": "Checklist Statuses",
            },
        ),
    ]
