# Generated by Django 5.1.3 on 2025-05-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0011_alter_checkliststatus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkliststatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
