# Generated by Django 5.1.3 on 2025-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0012_alter_checkliststatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="application_form",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/application_forms/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="application_form_compliance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checklist",
            name="application_form_remarks",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
