# Generated by Django 5.1.3 on 2025-05-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0014_remove_checklist_application_form_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklist",
            name="application_form_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="college_diploma_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="endorsement_contractor_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="endorsement_safety_manager_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="fee_permanent_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="fee_temporary_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="high_school_diploma_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="latest_photo_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="osh_new_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="osh_renewal_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="other_credentials_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="present_employment_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="previous_employment_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="proof_osh_committee_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="proof_osh_program_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="proof_other_reports_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="proof_safety_inspection_file",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="renewal_permit_file",
        ),
        migrations.AddField(
            model_name="checklist",
            name="application_form",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/application_forms/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="college_diploma",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/college_diplomas/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="endorsement_contractor",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/contractor_officials/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="endorsement_safety_manager",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/safety_manager/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="fee_permanent",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/permanent_safety_fee/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="fee_temporary",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/temporary_safety_fee/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="high_school_diploma",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/high_school_diplomas/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="latest_photo",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/photographs/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="osh_new",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/new_application_training/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="osh_renewal",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="checklist/renewal_application_training/",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="other_credentials",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/other_credentials/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="present_employment",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/present_employer/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="previous_employment",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/previous_employer/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="proof_osh_committee",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/csh_committee_reports/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="proof_osh_program",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/osh_shp_programs/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="proof_other_reports",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/other_reports/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="proof_safety_inspection",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/accident_reports/"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="renewal_permit",
            field=models.FileField(
                blank=True, null=True, upload_to="checklist/last_safety_permit/"
            ),
        ),
    ]
