# Generated by Django 5.1.3 on 2025-05-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0015_remove_checklist_application_form_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkliststatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("review", "Under Review"),
                ],
                max_length=20,
            ),
        ),
    ]
