# Generated by Django 5.1.3 on 2025-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0016_alter_checkliststatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkliststatus",
            name="approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
