# Generated by Django 5.1.3 on 2025-05-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0017_checkliststatus_approved_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkliststatus",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
